services:
  - type: web
    name: portfolio-mahima-site
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: portfolio_db
          property: host
      - key: DB_USER
        fromDatabase:
          name: portfolio_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portfolio_db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: portfolio_db
          property: database
      - key: DB_PORT
        fromDatabase:
          name: portfolio_db
          property: port

databases:
  - name: portfolio_db
    region: singapore
    plan: free
